# src/TypesenseBundle/Resources/config/services.yaml
services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    # Client de base Typesense (privé, utilisé par les autres services)
    Micka17\TypesenseBundle\Service\TypesenseClient:
        public: true # Essentiel pour que le projet puisse l'utiliser !
        arguments:
            $apiKey: '%env(TYPESENSE_API_KEY)%'
            $host: '%env(TYPESENSE_HOST)%'
            $port: '%env(TYPESENSE_PORT)%'
            $protocol: '%env(TYPESENSE_PROTOCOL)%'
        
    # Service public pour la gestion des collections et documents
    Micka17\TypesenseBundle\Service\TypesenseManager:
        public: true

    # Service public pour la recherche
    Micka17\TypesenseBundle\Service\TypesenseSearchService:
        public: true

    # Subscriber pour la mise à jour automatique des entités
    Micka17\TypesenseBundle\EventSubscriber\AutoUpdateSubscriber:
        arguments:
            $isEnabled: '%typesense.auto_update.enabled%'
            $indexedEntities: '%typesense.indexable_entities%'
        tags:
            - { name: 'doctrine.event_subscriber' }