# Fichier : micka-17/typesense-bundle/src/Resources/config/services.yaml
services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  # 1. Définition du Client : C'est ici que l'erreur se produit.
  # On doit lui fournir ses arguments.
  Micka17\TypesenseBundle\Service\TypesenseClient:
    public: true
    arguments:
      $apiKey: '%env(TYPESENSE_API_KEY)%'
      $host: '%env(TYPESENSE_HOST)%'
      $port: '%env(TYPESENSE_PORT)%'
      $protocol: '%env(TYPESENSE_PROTOCOL)%'

  # 2. Définition du Manager
  Micka17\TypesenseBundle\Service\TypesenseManager:
    public: true # Dépend du TypesenseClient, qui sera autowiré

  # 3. Définition du Normalizer
  Micka17\TypesenseBundle\Service\TypesenseNormalizer:
    arguments:
      $doctrine: '@doctrine'

  # 4. Définition du Listener
  Micka17\TypesenseBundle\EventListener\AutoUpdateListener:
    arguments:
      $isEnabled: '%typesense.auto_update.enabled%'
      $indexedEntities: '%typesense.indexable_entities%'
    tags:
      - { name: 'doctrine.event_listener', event: 'postPersist', method: 'postPersist' }
      - { name: 'doctrine.event_listener', event: 'postUpdate', method: 'postUpdate' }
      - { name: 'doctrine.event_listener', event: 'preRemove', method: 'preRemove' }