services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  # Le service TypesenseClient ne change pas
  Micka17\TypesenseBundle\Service\TypesenseClient:
    public: true
    arguments:
      $apiKey: '%env(TYPESENSE_API_KEY)%'
      $host: '%env(TYPESENSE_HOST)%'
      $port: '%env(TYPESENSE_PORT)%'
      $protocol: '%env(TYPESENSE_PROTOCOL)%'

  # Le service TypesenseManager est maintenant nécessaire pour le listener
  Micka17\TypesenseBundle\Service\TypesenseManager:
    public: true

  # NOUVELLE DÉCLARATION en tant que LISTENER
  Micka17\TypesenseBundle\EventListener\AutoUpdateListener:
    arguments:
      $isEnabled: '%typesense.auto_update.enabled%'
      $indexedEntities: '%typesense.indexable_entities%'

    # Au lieu d'un seul tag, on en met un pour chaque événement écouté
    tags:
      - { name: 'doctrine.event_listener', event: 'postPersist', method: 'postPersist' }
      - { name: 'doctrine.event_listener', event: 'postUpdate', method: 'postUpdate' }
      - { name: 'doctrine.event_listener', event: 'preRemove', method: 'preRemove' }